Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -106,7 +106,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard --repo $repoName --format json)  || (sleep 60 && str=$(scorecard --repo $repoName --format json))  || (sleep 60 && str=$(scorecard --repo $repoName --format json))   || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard --repo $repoName --format json)  || (sleep 60s && str=$(scorecard --repo $repoName --format json))  || (sleep 60s && str=$(scorecard --repo $repoName --format json))   || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TARGET_FILE 
                     echo "name:first  ${repoName} finished"
                     sleep 60s
@@ -131,7 +131,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-first --repo $repoName --format json)  || (sleep 60 &&str=$(scorecard-first --repo $repoName --format json))  || (sleep 60 &&str=$(scorecard-first --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-first --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-first --repo $repoName --format json))  || (sleep 60s && str=$(scorecard-first --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
                     echo $str >>  $TMP_FILE_FIRST
                     echo "name:second  ${repoName} finished"
                     sleep 60s
@@ -155,7 +155,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-second --repo $repoName --format json)  || (sleep 60 && str=$(scorecard-second --repo $repoName --format json))  || (sleep 60 && str=$(scorecard-second --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-second --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-second --repo $repoName --format json))  || (sleep 60s && str=$(scorecard-second --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_SECOND
                     echo "name third ${repoName} finished"
                     sleep 60s
@@ -181,7 +181,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-third --repo $repoName --format json)  || （sleep 60 &&str=$(scorecard-third --repo $repoName --format json)）||（sleep 60 &&str=$(scorecard-third --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-third --repo $repoName --format json)  || （sleep 60s &&str=$(scorecard-third --repo $repoName --format json)）||（sleep 60s &&str=$(scorecard-third --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_THIRD
                     echo "name:fourth ${repoName}  finished"
                     sleep 60s
@@ -205,7 +205,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-fourth --repo $repoName --format json)  || （sleep 60 && str=$(scorecard-fourth --repo $repoName --format json)）  || （sleep 60 && str=$(scorecard-fourth --repo $repoName --format json)） || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-fourth --repo $repoName --format json)  || （sleep 60s && str=$(scorecard-fourth --repo $repoName --format json)）  || （sleep 60s && str=$(scorecard-fourth --repo $repoName --format json)） || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_FOURTH
                     echo "name:fifth ${repoName}  finished"
                     sleep 60s
@@ -253,7 +253,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-sixth --repo $repoName --format json)  || （sleep 60 && str=$(scorecard-sixth --repo $repoName --format json)） || （sleep 60 && str=$(scorecard-sixth --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-sixth --repo $repoName --format json)  || （sleep 60s && str=$(scorecard-sixth --repo $repoName --format json)） || （sleep 60s && str=$(scorecard-sixth --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >>  $TMP_FILE_SIXTH
                     echo "name:seventh  ${repoName} finished"
                     sleep 60s
@@ -277,7 +277,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-seventh --repo $repoName --format json)  || （sleep 60 &&  str=$(scorecard-seventh --repo $repoName --format json)）||（sleep 60 &&  str=$(scorecard-seventh --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-seventh --repo $repoName --format json)  || （sleep 60s &&  str=$(scorecard-seventh --repo $repoName --format json)）||（sleep 60s &&  str=$(scorecard-seventh --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_SEVENTH
                     echo "name:eighth ${repoName} finished"
                     sleep 60s
@@ -286,7 +286,7 @@ jobs:
                  
               }&
               echo "name:eighth"
-              sleep 60s
+              sleep 80s
           done
           
           
