Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -95,19 +95,18 @@ jobs:
               echo "count value :${count}"
               read -u5
               {
-                if [ `expr ${count} % 2` -eq 0 ]; then
+                if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN }}
-                else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN9 }}
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN17 }}
                 fi
                 if [ $i -lt $length ];then
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard --repo $repoName --format json)  || (sleep 60 && str=$(scorecard --repo $repoName --format json))  || (sleep 60 && str=$(scorecard --repo $repoName --format json))   || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TARGET_FILE 
                     echo "name:first  ${repoName} finished"
                     sleep 60s
@@ -119,10 +118,12 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                if [ `expr ${count} % 2` -eq 0 ]; then
+                if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN2 }}
-                else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN10 }}
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN118 }}
                 fi
                 
                 if [ $i -lt $length ];then
@@ -130,10 +131,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-first --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-first --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-first --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-first --repo $repoName --format json)  || (sleep 60 &&str=$(scorecard-first --repo $repoName --format json))  || (sleep 60 &&str=$(scorecard-first --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
                     echo $str >>  $TMP_FILE_FIRST
                     echo "name:second  ${repoName} finished"
                     sleep 60s
@@ -144,21 +142,20 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                if [ `expr ${count} % 2` -eq 0 ]; then
+                if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN3 }}
-                 else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN11 }}
-                 fi
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN19}}
+                fi
                  
                  if [ $i -lt $length ];then
                     
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-second --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-second --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-second --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-second --repo $repoName --format json)  || (sleep 60 && str=$(scorecard-second --repo $repoName --format json))  || (sleep 60 && str=$(scorecard-second --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_SECOND
                     echo "name third ${repoName} finished"
                     sleep 60s
@@ -170,11 +167,13 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                 if [ `expr ${count} % 2` -eq 0 ]; then
-                  export GH_TOKEN=${{ secrets.GH_TOKEN4 }}
-                 else
-                  export GH_TOKEN=${{ secrets.GH_TOKEN12 }}
-                 fi
+                if [ `expr ${count} % 3` -eq 0 ]; then
+                  export GH_TOKEN=${{ secrets.GH_TOKEN4}}
+                elif [ `expr ${count} % 3` -eq 1 ]; then
+                  export GH_TOKEN=${{ secrets.GH_TOKEN12}
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN20}
+                fi
                  
                  
                  if [ $i -lt $length ];then
@@ -182,10 +181,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-third --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-third --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-third --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-third --repo $repoName --format json)  || （sleep 60 &&str=$(scorecard-third --repo $repoName --format json)）||（sleep 60 &&str=$(scorecard-third --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_THIRD
                     echo "name:fourth ${repoName}  finished"
                     sleep 60s
@@ -197,20 +193,19 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                 if [ `expr ${count} % 2` -eq 0 ]; then
+                if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN5 }}
-                 else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN13 }}
-                 fi
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN21 }}
+                fi
                  i=$(($i+1))
                  if [ $i -lt $length ];then
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-fourth --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-fourth --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-fourth --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-fourth --repo $repoName --format json)  || （sleep 60 && str=$(scorecard-fourth --repo $repoName --format json)）  || （sleep 60 && str=$(scorecard-fourth --repo $repoName --format json)） || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_FOURTH
                     echo "name:fifth ${repoName}  finished"
                     sleep 60s
@@ -222,20 +217,19 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                 if [ `expr ${count} % 2` -eq 0 ]; then
+                if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN6 }}
-                 else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN14 }}
-                 fi
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN22 }}
+                fi
 
                  if [ $i -lt $length ];then
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-fifth --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-fifth --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-fifth --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-fifth --repo $repoName --format json)  || （sleep 60 &&  str=$(scorecard-fifth --repo $repoName --format json)） ||（sleep 60 &&  str=$(scorecard-fifth --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_FIFTH
                     echo "name:sixth  ${repoName} finished"
                     sleep 60s
@@ -247,20 +241,19 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                 if [ `expr ${count} % 2` -eq 0 ]; then
+                 if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN7 }}
-                else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN15 }}
-                 fi
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN23 }}
+                fi
                 
                 if [ $i -lt $length ];then
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-sixth --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-sixth --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-sixth --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-sixth --repo $repoName --format json)  || （sleep 60 && str=$(scorecard-sixth --repo $repoName --format json)） || （sleep 60 && str=$(scorecard-sixth --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >>  $TMP_FILE_SIXTH
                     echo "name:seventh  ${repoName} finished"
                     sleep 60s
@@ -272,20 +265,19 @@ jobs:
               i=$(($i+1))
               read -u5
               {
-                 if [ `expr ${count} % 2` -eq 0 ]; then
+                 if [ `expr ${count} % 3` -eq 0 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN8 }}
-                 else
+                elif [ `expr ${count} % 3` -eq 1 ]; then
                   export GH_TOKEN=${{ secrets.GH_TOKEN16 }}
-                 fi
+                else
+                  export GH_TOKEN=${{ secrets.GH_TOKEN24 }}
+                fi
                  
                  if [ $i -lt $length ];then
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-seventh --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-seventh --repo $repoName --format json)  || sleep 2|
-                    str=$(scorecard-seventh --repo $repoName --format json)  ||
-                    str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-seventh --repo $repoName --format json)  || （sleep 60 &&  str=$(scorecard-seventh --repo $repoName --format json)）||（sleep 60 &&  str=$(scorecard-seventh --repo $repoName --format json)）|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_SEVENTH
                     echo "name:eighth ${repoName} finished"
                     sleep 60s
