Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -109,7 +109,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard --repo $repoName --format json)  || (sleep 60s | str=$(scorecard --repo $repoName --format json))  || (sleep 60s | str=$(scorecard --repo $repoName --format json))   || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard --repo $repoName --format json)  || (sleep 60s && str=$(scorecard --repo $repoName --format json))  || (sleep 60s && str=$(scorecard --repo $repoName --format json))   || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TARGET_FILE 
                     echo "name:first  ${repoName} finished"
                     echo >&5
@@ -134,7 +134,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-first --repo $repoName --format json)  || (sleep 60s | str=$(scorecard-first --repo $repoName --format json))  || (sleep 60s | str=$(scorecard-first --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-first --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-first --repo $repoName --format json))  || (sleep 60s && str=$(scorecard-first --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
                     echo $str >>  $TMP_FILE_FIRST
                     echo "name:second  ${repoName} finished"
                     echo >&5
@@ -158,7 +158,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-second --repo $repoName --format json)  || (sleep 60s | str=$(scorecard-second --repo $repoName --format json))  || (sleep 60s  str=$(scorecard-second --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-second --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-second --repo $repoName --format json))  || (sleep 60s && str=$(scorecard-second --repo $repoName --format json))  || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_SECOND
                     echo "name third ${repoName} finished"
                     echo >&5
@@ -184,7 +184,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-third --repo $repoName --format json)  || (sleep 60s | str=$(scorecard-third --repo $repoName --format json))||(sleep 60s | str=$(scorecard-third --repo $repoName --format json)) || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-third --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-third --repo $repoName --format json))||(sleep 60s && str=$(scorecard-third --repo $repoName --format json)) || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_THIRD
                     echo "name:fourth ${repoName}  finished"
                     echo >&5
@@ -207,7 +207,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-fourth --repo $repoName --format json)  || (sleep 60s | str=$(scorecard-fourth --repo $repoName --format json))  || (sleep 60s | str=$(scorecard-fourth --repo $repoName --format json)) || str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-fourth --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-fourth --repo $repoName --format json))  || (sleep 60s && str=$(scorecard-fourth --repo $repoName --format json)) || str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_FOURTH
                     echo "name:fifth ${repoName}  finished"
                     echo >&5
@@ -231,7 +231,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-fifth --repo $repoName --format json)  || (sleep 60 |  str=$(scorecard-fifth --repo $repoName --format json)) ||(sleep 60 |  str=$(scorecard-fifth --repo $repoName --format json))|| str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-fifth --repo $repoName --format json)  || (sleep 60 && str=$(scorecard-fifth --repo $repoName --format json)) ||(sleep 60 && str=$(scorecard-fifth --repo $repoName --format json))|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_FIFTH
                     echo "name:sixth  ${repoName} finished"
                     echo >&5
@@ -255,7 +255,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-sixth --repo $repoName --format json)  || (sleep 60s | str=$(scorecard-sixth --repo $repoName --format json)) || (sleep 60s | str=$(scorecard-sixth --repo $repoName --format json))|| str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-sixth --repo $repoName --format json)  || (sleep 60s && str=$(scorecard-sixth --repo $repoName --format json)) || (sleep 60s && str=$(scorecard-sixth --repo $repoName --format json))|| str=$(echo "faild on ${repoName}") 
                     echo $str >>  $TMP_FILE_SIXTH
                     echo "name:seventh  ${repoName} finished"
                     echo >&5
@@ -279,7 +279,7 @@ jobs:
                     repoName=https://github.com/laiyoufafa/${arr[$i]}
                     echo "time:${i}    repos_url:${repoName} "
                     str=""
-                    str=$(scorecard-seventh --repo $repoName --format json)  || (sleep 60s |  str=$(scorecard-seventh --repo $repoName --format json))||(sleep 60s |  str=$(scorecard-seventh --repo $repoName --format json))|| str=$(echo "faild on ${repoName}") 
+                    str=$(scorecard-seventh --repo $repoName --format json)  || (sleep 60s &&  str=$(scorecard-seventh --repo $repoName --format json))||(sleep 60s &&  str=$(scorecard-seventh --repo $repoName --format json))|| str=$(echo "faild on ${repoName}") 
                     echo $str >> $TMP_FILE_SEVENTH
                     echo "name:eighth ${repoName} finished"
                     echo >&5
